name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "CI_CD_FastApi/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      working-directory: CI_CD_FastApi
      run: docker build . -t pizza-quality-service:latest