name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'CI_CD_FastApi/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'CI_CD_FastApi/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      # We specify the exact path to the Dockerfile and set the build context folder
      run: |
        docker build \
          --file CI_CD_FastApi/Dockerfile \
          --tag pizza-quality-service:$(date +%s) \
          CI_CD_FastApi
